using System.Collections;
using System.Collections.Generic;
using UnityEngine;
 
public abstract class Breaker : MonoBehaviour
{
    public bool isOpened;
    public float delay;
    public bool automaticOpen;
    public float automaticOpenDelay;

    protected Material ledUpMat;
    protected Material ledDownMat;
    private bool isHighlighted;
    private string colliderName; 
    private Transform armWrapper;
    private Material roundedBoxMat;
    private Material armMat;
    private DetectSelection fpsSelection;
    private AudioSource audioSource;
    private Vector3 closedAngle = new Vector3(-30, 0, 0);
    private Vector3 openedAngle = new Vector3(30, 0, 0);
    private float timeClicked;

    protected void BreakerStart()
    {
        // Reach for important components in this game object
        fpsSelection = GameObject.Find("FPS").GetComponent<DetectSelection>(); 
        audioSource = transform.Find("Body/Sound").gameObject.GetComponent<AudioSource>();
        armWrapper = transform.Find("Body/ArmWrapper");
        armMat = transform.Find("Body/ArmWrapper/Arm").GetComponent<Renderer>().material;
        timeClicked = Mathf.Infinity;
        roundedBoxMat = transform.Find("Body/RoundedBoxWrapper/RoundedBox").GetComponent<Renderer>().material;
        isHighlighted = false;

        // Collider objects must be renamed for the DetectSelection script
        colliderName = gameObject.name + ": collider <generated by script>";
        transform.Find("Body/ArmWrapper/Arm").gameObject.name = colliderName;
        transform.Find("Body/RoundedBoxWrapper/RoundedBox").gameObject.name = colliderName;
        // Starting position for the breaker
        if (isOpened)
        {
            OpenBreaker();
            OpenSpecific();
        }
        else
        {
            CloseBreaker();
            CloseSpecific();
        }
    }

    void Update()
    {
        if (automaticOpen && Time.timeSinceLevelLoad > automaticOpenDelay)
        {
            automaticOpen = false;
            ActivateButton();
        }
        else if (fpsSelection.lastSelectedName == colliderName)
        {
            fpsSelection.Clear();
            ActivateButton();
        }

        if ( Time.time > (timeClicked + delay) )
        {
            if (isOpened)
            {
                OpenSpecific();
            }
            else
            {
                CloseSpecific();
            }
            AfterDelaySpecific();
            timeClicked = Mathf.Infinity;
        }
    }

    void ActivateButton()
    {
        timeClicked = Time.time;
        OnClickSpecific();

        if (isOpened)
        {
            CloseBreaker();
        }
        else
        {
            OpenBreaker();
        }

        audioSource.Play();
        isOpened = !isOpened;
    }

    void CloseBreaker()
    {
        armWrapper.localEulerAngles = closedAngle;
        //armMat.SetVector("_Color", ledDownMat.GetVector("_Color"));
        ledDownMat.EnableKeyword("_EMISSION");
        ledUpMat.DisableKeyword("_EMISSION");
    }

    void OpenBreaker()
    {
        armWrapper.localEulerAngles = openedAngle;
        //armMat.SetVector("_Color", ledUpMat.GetVector("_Color"));
        ledUpMat.EnableKeyword("_EMISSION");
        ledDownMat.DisableKeyword("_EMISSION");
    }

    private void LateUpdate()
    {
        if (!isHighlighted && (fpsSelection.lastHoveredName == colliderName))
        {
            isHighlighted = true;
            roundedBoxMat.SetFloat("_FirstOutlineWidth", 0.2f);
        }
        else if (isHighlighted && (fpsSelection.lastHoveredName != colliderName))
        {
            isHighlighted = false;
            roundedBoxMat.SetFloat("_FirstOutlineWidth", 0f);
        }
    }

    public abstract void CloseSpecific();
    public  abstract void OpenSpecific();
    public abstract void OnClickSpecific();
    public abstract void AfterDelaySpecific();

}
